apiVersion: v2
appVersion: "1.0"
description: Divorce - Case Maintenance Service
name: div-cms
version: 2.0.14
dependencies:
    - name: java
      version: 4.2.0
      repository: "https://hmctspublic.azurecr.io/helm/v1/repo/"
