java:
    applicationPort: 4010
    aadIdentityName: divorce
    ingressHost: "div-cms-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    environment:
        AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DRAFT_STORE_API_BASEURL: "http://draft-store-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        CASE_FORMATTER_SERVICE_API_BASEURL: "http://div-cfs-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        IDAM_API_REDIRECT_URL: "https://div-pfe-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/authenticated"
        CASE_DATA_STORE_BASEURL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE: "divorce_ccd_submission"
        AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: "900"
        LOG_LEVEL: DEBUG
        MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
        DOCUMENTATION_SWAGGER_ENABLED: true
    keyVaults:
        "div":
            resourceGroup: div
            secrets:
                - ccd-submission-s2s-auth-secret
                - idam-secret
                - draft-store-api-encryption-key
                - idam-caseworker-username
                - idam-caseworker-password
